config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

]
urlpatterns+=[
    path("", include("home.urls")),
    path("estudiantes/", include("estudiantes.urls")),
    path("profesores/", include("profesores.urls")),
    path("cursos/", include("cursos.urls")),
]

cursos/urls.py
from django.urls import path
from . import views

app_name="cursos"

urlpatterns = [
    path("",views.CursosList.as_view(),name="cursos_list"),
    path("detail/<int:pk>",views.CursosDetail.as_view(),name="cursos_detail"),
    path("crear/",views.CursosCreate.as_view(),name="cursos_create"),
    path("actualizar/<int:pk>",views.CursosUpdate.as_view(),name="cursos_update"),
    path("borrar/<int:pk>",views.CursosDelete.as_view(),name="cursos_delete"),
]

estudiantes/urls.py
from django.views.generic import TemplateView
from django.urls import path
from . import views

app_name="estudiantes"

urlpatterns = [
    path("",views.EstudiantesList.as_view(),name="estudiantes_list"),
    path("detail/<int:pk>",views.EstudiantesDetail.as_view(),name="estudiantes_detail"),
    path("crear/",views.EstudiantesCreate.as_view(),name="estudiantes_create"),
    path("actualizar/<int:pk>",views.EstudiantesUpdate.as_view(),name="estudiantes_update"),
    path("borrar/<int:pk>",views.EstudiantesDelete.as_view(),name="estudiantes_delete"),
]

home/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name="home"

urlpatterns = [
    path("",views.index, name="index"),
    path("about/",views.about, name="about"),
    path("login/",views.login_request, name="login"),
    path("register/",views.register, name="register"),
    path("logout/",LogoutView.as_view(template_name="home/index.html"), name="logout")
]
urlpatterns += staticfiles_urlpatterns()

profesores/urls.py
from django.urls import path
from . import views

app_name="profesores"

urlpatterns = [
    path("",views.ProfesoresList.as_view(),name="profesores_list"),
    path("detail/<int:pk>",views.ProfesoresDetail.as_view(),name="profesores_detail"),
    path("crear/",views.ProfesoresCreate.as_view(),name="profesores_create"),
    path("actualizar/<int:pk>",views.ProfesoresUpdate.as_view(),name="profesores_update"),
    path("borrar/<int:pk>",views.ProfesoresDelete.as_view(),name="profesores_delete"),
]

home/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms
from django.contrib.auth.forms import UserModel, UserCreationForm,AuthenticationForm


class UserCreationFormCustom(UserCreationForm):
    username= forms.CharField(
        label="Nombre de usuario",
        widget=forms.TextInput(attrs={"class":"form-control"})
    )
    password1= forms.CharField(
        label="Contraseña",
        widget=forms.PasswordInput(attrs={"class":"form-control"})
    )
    password2= forms.CharField(
        label="Repetir Contraseña",
        widget=forms.PasswordInput(attrs={"class":"form-control"})
    )
    class Meta:
        model= UserModel
        fields=["username","password1","password2"]
        help_text= {
            k:"" for k in fields
        }
    
class AuthenticationFormCustom(AuthenticationForm):
    username= forms.CharField(
        label="Nombre de usuario",
        widget=forms.TextInput(attrs={"class":"form-control"})
    )
    password= forms.CharField(
        label="Contraseña",
        widget=forms.PasswordInput(attrs={"class":"form-control"})
    )
    class Meta:
        model= UserModel
        fields=["username","password1","password2"]
        help_text= {
            k:"" for k in fields
        }

home/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout


from home.forms import UserCreationFormCustom,AuthenticationFormCustom
# Create your views here.

def index(request):
    
    return render(request, "home/index.html")

def about(request):
    return render(request, "home/about.html")

def login_request(request):
    if request.method == "POST":
        form = AuthenticationFormCustom(request, data=request.POST)
        if form.is_valid():
            usuario = form.cleaned_data.get('username')
            contrasena = form.cleaned_data.get('password')
            user = authenticate(username=usuario, password=contrasena)
            login(request, user)
            return render(request, "home/index.html")
    else:
        form = AuthenticationFormCustom()
    return render(request, "home/login.html", {"form": form})

def register(request):
    if request.method == "POST":
        form = UserCreationFormCustom(request.POST)
        if form.is_valid():
            usuario = form.cleaned_data['username']
            form.save()
            return render(request, "home/index.html")
    else:
        form = UserCreationFormCustom()
    return render(request, "home/register.html", {"form": form})

home/templates/home/about.html
{% extends 'home/index.html' %}
{% load static %}
{% block titulo %}
<title>About</title>
{% endblock titulo %}
{% block tittle %}
    <h1>Acerca de mí</h1>
{% endblock tittle %}

{% block content-left %}
<div class="spinner-border text-danger" role="status">
    <span class="visually-hidden">Sitio en construccion...</span>
</div>
<img src="{% static 'home/assets/leo.jpg' %}" class="img-fluid rounded-circle float-start" alt="">
<p>Mi nombre es <strong>Leonardo Heffel</strong>, Fullstack Developer en proceso de creacion de mi primer sitio web con <strong>Django</strong> </p>
<p>Pueden saber mas acerca de mi y de mis proyectos en  <a href="https://www.linkedin.com/in/leonardo-heffel/">LinkedIn</a></p>
{% endblock content-left %}

{% block content-right %}
  <div class="p-3" > <a href="{% url 'home:index' %}"><button class="btn btn-secondary">Volver <i class="bi bi-arrow-left-square-fill"></i></button></a></div>
    
{% endblock content-right %}

home/templates/home/index.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block titulo %}
      <title>My App with Djanjo</title>
    {% endblock titulo %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
    {% block nav %}
    <div class="container">
        <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
          <div class="col-md-3 mb-2 mb-md-0">
            <a href="/" class="d-inline-flex link-body-emphasis text-decoration-none">
              <svg class="bi" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
            </a>
          </div>
    
          <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
            <li><a href="/" class="nav-link px-2 ">Home</a></li>
            <li><a href="{% url 'estudiantes:estudiantes_list' %}" class="nav-link px-2">Estudiantes</a></li>
            <li><a href="{% url 'profesores:profesores_list' %}" class="nav-link px-2">Profesores</a></li>
            <li><a href="{% url 'cursos:cursos_list' %}" class="nav-link px-2">Cursos</a></li>
            <li><a href="/about" class="nav-link px-2">About</a></li>
          </ul>
          

           
          <div class="col-md-3 text-end">
            {% if user.is_authenticated %}
              <button type="button" class="btn btn-danger"><a href="{% url 'home:logout' %}" class="nav-link px-2">Salir</a></button>
            {% else %}
              <button type="button" class="btn btn-outline-primary me-2"><a href="{% url 'home:login' %}" class="nav-link px-2">Login</a></button>
              <button type="button" class="btn btn-primary"><a href="{% url 'home:register' %}" class="nav-link px-2">Registrarse</a></button>
            {% endif %}
           
          </div>
        </header>
      </div>
     
    {% endblock nav %}
    
    <div class="container">
      {% block tittle %}
      {% if user.is_authenticated %} <h4>Hola {{ user.username }}</h4> {% endif %}
      {% endblock tittle %}
    </div>

    <div class="container text-center">
        <div class="row align-items-center">
          <div class="col">

            {% block content-left %}
                <img src="{% static 'home/assets/background.jpg' %}" class="img-fluid rounded float-start" alt="">
            {% endblock content-left %}
          </div>
          <div class="col">
            {% block content-right %}
                <h2>Mi primera web con django</h2>
            {% endblock content-right %}
          </div>
        </div>
      </div>
  

      <div class="container text-center">
        <div class="row align-items-end">
          <div class="col">
            {% block footer %}
    
            <div class="container fixed-bottom">
                
                <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
                  <div class="col-md-4 d-flex align-items-center">
                    <a href="/" class="mb-3 me-2 mb-md-0 text-body-secondary text-decoration-none lh-1">
                      <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
                    </a>
                    <span class="mb-3 mb-md-0 text-body-secondary">© 2023 Company, Inc</span>
                  </div>
              
                  <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
                    <li class="ms-3"><a class="text-body-secondary" href="#"></a></li>
                    <li class="ms-3"><a class="text-body-secondary" href="#"></a></li>
                    <li class="ms-3"><a class="text-body-secondary" href="#"></use></svg></a></li>
                  </ul>
                </footer>
              </div>
            {% endblock footer %}
            
          </div>
        </div>
      </div>


    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

home/templates/home/login.html
{% extends 'home/index.html' %}
{% block titulo %}
<title>About</title>
{% endblock titulo %}
{% block tittle %}
    <h1>Login </h1>
{% endblock tittle %}

{% block content-left %}
<form action="" method="post">
  <div class="mb-3">
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit" class="btn btn-primary" >Iniciar Sesion</button>
  </div>
</form>
{% endblock content-left %}

{% block content-right %}
<a href="{% url 'home:register' %}"><button class="btn btn-primary">Deseas Registrarte</button></a>
<div class="p-3" > <a href="{% url 'home:index' %}"><button class="btn btn-secondary">Volver <i class="bi bi-arrow-left-square-fill"></i></button></a></div>
    
{% endblock content-right %}

home/templates/home/register.html
{% extends 'home/index.html' %}
{% block titulo %}
<title>About</title>
{% endblock titulo %}
{% block tittle %}
    <h1>Registro </h1>
{% endblock tittle %}

{% block content-left %}
<form action="" method="post">
  <div class="mb-3">
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit" class="btn btn-primary" >Registrame</button>
  </div>
</form>
{% endblock content-left %}

{% block content-right %}
<a href="{% url 'home:login' %}"><button class="btn btn-primary">Deseas Iniciar Sesion?</button></a>
<div class="p-3" > <a href="{% url 'home:index' %}"><button class="btn btn-secondary">Volver <i class="bi bi-arrow-left-square-fill"></i></button></a></div>
    
{% endblock content-right %}