config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

]
urlpatterns+=[
    path("", include("home.urls")),
    path("estudiantes/", include("estudiantes.urls")),
    path("profesores/", include("profesores.urls")),
    path("cursos/", include("cursos.urls")),
]

estudiantes/urls.py
from django.views.generic import TemplateView
from django.urls import path
from . import views

app_name="estudiantes"

urlpatterns = [
    path("",views.EstudiantesList.as_view(),name="estudiantes_list"),
    path("detail/<int:pk>",views.EstudiantesDetail.as_view(),name="estudiantes_detail"),
    path("crear/",views.EstudiantesCreate.as_view(),name="estudiantes_create"),
    path("actualizar/<int:pk>",views.EstudiantesUpdate.as_view(),name="estudiantes_update"),
    path("borrar/<int:pk>",views.EstudiantesDelete.as_view(),name="estudiantes_delete"),
]

home/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name="home"

urlpatterns = [
    path("",views.index, name="index"),
    path("about/",views.about, name="about"),
    path("login/",views.login_request, name="login"),
    path("register/",views.register, name="register"),
    path("logout/",LogoutView.as_view(template_name="home/index.html"), name="logout")
]
urlpatterns += staticfiles_urlpatterns()

estudiantes/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Estudiante(models.Model):
    nombre=models.CharField(max_length=100)
    apellido=models.CharField(max_length=100)
    nacimiento=models.DateField(null=True, blank=True)
    # curso=models.ForeignKey(Curso, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self) -> str:
        return f"{self.nombre} {self.apellido}"
    ##def get_absolute_url(self):
      ##  return reverse('estudiantes:estudiantes_list')

estudiantes/forms.py
from django import forms
from . import models

class EstudianteForm(forms.ModelForm):
    class Meta:
        model= models.Estudiante
        fields=["nombre","apellido","nacimiento"]

        widgets= {
            "nombre":forms.TextInput(attrs={"class":"form-control"}),
            "apellido":forms.TextInput(attrs={"class":"form-control"}),
            "nacimiento":forms.DateInput(attrs={"class":"form-control"})
        }

estudiantes/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView , DeleteView
from . import models
from . import forms


# Create your views here.

class EstudiantesList(ListView):
    model = models.Estudiante

    def get_queryset(self):
        object_list = models.Estudiante.objects.all()
        if self.request.GET.get("buscar"):
            consulta = self.request.GET.get("buscar")
            object_list = models.Estudiante.objects.filter(
                nombre__icontains=consulta
            )
        return object_list

class EstudiantesDetail(DetailView):
    model = models.Estudiante

class EstudiantesCreate(LoginRequiredMixin,CreateView):
    login_url = 'home:login'
    model = models.Estudiante
    form_class = forms.EstudianteForm
    success_url=reverse_lazy("estudiantes:estudiantes_list")

class EstudiantesUpdate(LoginRequiredMixin,UpdateView):
    login_url = 'home:login'
    model = models.Estudiante
    form_class = forms.EstudianteForm
    success_url=reverse_lazy("estudiantes:estudiantes_list")

class EstudiantesDelete(LoginRequiredMixin,DeleteView):
    login_url = 'home:login'
    model = models.Estudiante
    success_url=reverse_lazy("estudiantes:estudiantes_list")

estudiantes/templates/estudiantes/crear.html
{% extends 'home/index.html' %}

{% block tittle %}
    <h1>CREAR ESTUDIANTE </h1>
{% endblock tittle %}

{% block content-left %}
    <form action="" method="post">
        <div class="mb-3">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary" >Guardar</button>
        </div>
    </form>


{% endblock content-left %}

{% block content-right %}

{% endblock content-right %}

estudiantes/templates/estudiantes/estudiante_confirm_delete.html
{% extends 'home/index.html' %}

{% block titulo %}
    <title>Estudiantes</title>
{% endblock titulo %}

{% block tittle %}
<div class="container">
    <h1>Eliminar estudiante </h1>
</div>
    
{% endblock tittle %}

{% block content-left %}
  <p> esta seguro que desea eliminar {{object.nombre}} {{object.apellido}}?</p>
  <form action="" method="post">
    <div class="mb-3">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-danger" >Eliminar</button>
    </div>
</form>
{% endblock content-left %}

    
{% block content-right %}
    <a href="{% url 'estudiantes:estudiantes_list' %}"><button class="btn btn-secondary">Volver <i class="bi bi-arrow-left-square-fill"></i></button></a>
{% endblock content-right %}

estudiantes/templates/estudiantes/estudiante_detail.html
{% extends 'home/index.html' %}

{% block titulo %}
    <title>Estudiantes</title>
{% endblock titulo %}

{% block tittle %}
<div class="container">
    <h1>Detalles de estudiante </h1>
</div>
    
{% endblock tittle %}

{% block content-left %}
    <ul class="list-group">
       
        <li class="list-group-item list-group-item-info"><strong>Nombre:</strong>  {{object.nombre}} </li>
        <li class="list-group-item list-group-item-info"> Apellido: {{object.apellido}}  </li>
        <li class="list-group-item list-group-item-info"> Fecha de Nacimiento: {{object.nacimiento}} </li>
        

    </ul>
    
{% endblock content-left %}

    
{% block content-right %}
<a href="{% url 'estudiantes:estudiantes_update' estudiante.id %}"><button class="btn btn-warning">Editar<i class="bi bi-pencil-square"></i></button></a>
<a href="{% url 'estudiantes:estudiantes_delete' estudiante.id %}"><button class="btn btn-danger">Eliminar<i class="bi bi-trash-fill"></i></button></a>
<div class="p-3" > <a href="{% url 'estudiantes:estudiantes_list' %}"><button class="btn btn-secondary">Volver <i class="bi bi-arrow-left-square-fill"></i></button></a></div>
    
{% endblock content-right %}

estudiantes/templates/estudiantes/estudiante_form.html
{% extends 'home/index.html' %}

{% block tittle %}
    <h1>CREAR ESTUDIANTE </h1>
{% endblock tittle %}

{% block content-left %}
    <form action="" method="post">
        <div class="mb-3">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary" >Guardar</button>
        </div>
    </form>


{% endblock content-left %}

{% block content-right %}
<div class="p-3" > <a href="{% url 'estudiantes:estudiantes_list' %}"><button class="btn btn-secondary">Volver <i class="bi bi-arrow-left-square-fill"></i></button></a></div>
{% endblock content-right %}

estudiantes/templates/estudiantes/estudiante_list.html
{% extends 'home/index.html' %}

{% block titulo %}
    <title>Estudiantes</title>
{% endblock titulo %}

{% block tittle %}
<div class="container">
    <h1>Listado de estudiantes </h1>
</div>
    
{% endblock tittle %}

{% block content-left %}
    <div class="py-4 text-center">
        <form action="" method="GET">
            <input type="text" name="buscar" placeholder="Buscar" class="form-control"> 
            <button class="btn btn-primary m-2" type="submit">Buscar</button>
            <button class="btn btn-primary m-2" >Todos</button>
        </form>
    </div>

    <ul class="list-group">
        {% for estudiante in object_list %}
        <li class="list-group-item list-group-item-info"> {{estudiante.nombre}}  {{estudiante.apellido}}
            <a class="float-end" href="{% url 'estudiantes:estudiantes_detail' estudiante.id %}"><button class="btn btn-info">Detalles <i class="bi bi-eye"></i></button></a>
        </li>
        
      
    {% endfor %}

    </ul>
    
{% endblock content-left %}
  
{% block content-right %}

    <a href="{% url 'estudiantes:estudiantes_create' %}"><button class="btn btn-success">Agregar <i class="bi bi-file-earmark-plus"></i></button></a>
    <div class="p-3" > <a href="{% url 'home:index' %}"><button class="btn btn-secondary">Volver <i class="bi bi-arrow-left-square-fill"></i></button></a></div>
{% endblock content-right %}