config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

]
urlpatterns+=[
    path("", include("home.urls")),
    path("estudiantes/", include("estudiantes.urls")),
    path("profesores/", include("profesores.urls")),
    path("cursos/", include("cursos.urls")),
]

home/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name="home"

urlpatterns = [
    path("",views.index, name="index"),
    path("about/",views.about, name="about"),
    path("login/",views.login_request, name="login"),
    path("register/",views.register, name="register"),
    path("logout/",LogoutView.as_view(template_name="home/index.html"), name="logout")
]
urlpatterns += staticfiles_urlpatterns()

profesores/urls.py
from django.urls import path
from . import views

app_name="profesores"

urlpatterns = [
    path("",views.ProfesoresList.as_view(),name="profesores_list"),
    path("detail/<int:pk>",views.ProfesoresDetail.as_view(),name="profesores_detail"),
    path("crear/",views.ProfesoresCreate.as_view(),name="profesores_create"),
    path("actualizar/<int:pk>",views.ProfesoresUpdate.as_view(),name="profesores_update"),
    path("borrar/<int:pk>",views.ProfesoresDelete.as_view(),name="profesores_delete"),
]

profesores/models.py
from django.db import models

# Create your models here.
class Profesor(models.Model):
    nombre=models.CharField(max_length=100)
    apellido=models.CharField(max_length=100)
    email=models.EmailField(max_length=200)
    # curso=models.ForeignKey(Curso, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self) -> str:
        return f"{self.nombre} {self.apellido}"

profesores/forms.py
from django import forms
from . import models

class ProfesorForm(forms.ModelForm):
    class Meta:
        model= models.Profesor
        fields=["nombre","apellido","email"]

        widgets= {
            "nombre":forms.TextInput(attrs={"class":"form-control"}),
            "apellido":forms.TextInput(attrs={"class":"form-control"}),
            "email":forms.EmailInput(attrs={"class":"form-control"})
        }
    

profesores/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView , DeleteView
from . import models
from . import forms


# Create your views here.

class ProfesoresList(ListView):
    model = models.Profesor

    def get_queryset(self):
        object_list = models.Profesor.objects.all()
        if self.request.GET.get("buscar"):
            consulta = self.request.GET.get("buscar")
            object_list = models.Profesor.objects.filter(
                nombre__icontains=consulta
            )
        return object_list

class ProfesoresDetail(DetailView):
    model = models.Profesor

class ProfesoresCreate(LoginRequiredMixin,CreateView):
    login_url = 'home:login'
    model = models.Profesor
    form_class = forms.ProfesorForm
    success_url=reverse_lazy("profesores:profesores_list")

class ProfesoresUpdate(LoginRequiredMixin,UpdateView):
    login_url = 'home:login'
    model = models.Profesor
    form_class = forms.ProfesorForm
    success_url=reverse_lazy("profesores:profesores_list")

class ProfesoresDelete(LoginRequiredMixin,DeleteView):
    login_url = 'home:login'
    model = models.Profesor
    success_url=reverse_lazy("profesores:profesores_list")

profesores/templates/profesores/crear.html
{% extends 'home/index.html' %}

{% block tittle %}
    <h1>CREAR PROFESOR </h1>
{% endblock tittle %}

{% block content-left %}
    <form action="" method="post">
        <div class="mb-3">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary" >Guardar</button>
        </div>
    </form>


{% endblock content-left %}

{% block content-right %}

{% endblock content-right %}

profesores/templates/profesores/profesor_confirm_delete.html
{% extends 'home/index.html' %}

{% block titulo %}
    <title>Profesores</title>
{% endblock titulo %}

{% block tittle %}
<div class="container">
    <h1>Eliminar profesor </h1>
</div>
    
{% endblock tittle %}

{% block content-left %}
  <p> esta seguro que desea eliminar {{object.nombre}} {{object.apellido}}?</p>
  <form action="" method="post">
    <div class="mb-3">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-danger" >Eliminar</button>
    </div>
</form>
{% endblock content-left %}

    
{% block content-right %}
    <a href="{% url 'profesores:profesores_list' %}"><button class="btn btn-secondary">Volver <i class="bi bi-arrow-left-square-fill"></i></button></a>
{% endblock content-right %}

profesores/templates/profesores/profesor_detail.html
{% extends 'home/index.html' %}

{% block titulo %}
    <title>Estudiantes</title>
{% endblock titulo %}

{% block tittle %}
<div class="container">
    <h1>Detalles de profesor </h1>
</div>
    
{% endblock tittle %}

{% block content-left %}
    <ul class="list-group">
       
        <li class="list-group-item list-group-item-info"><strong>Nombre:</strong>  {{object.nombre}} </li>
        <li class="list-group-item list-group-item-info"> Apellido: {{object.apellido}}  </li>
        <li class="list-group-item list-group-item-info"> Email: {{object.email}} </li>
        

    </ul>
    
{% endblock content-left %}

    
{% block content-right %}
<a href="{% url 'profesores:profesores_update' profesor.id %}"><button class="btn btn-warning">Editar<i class="bi bi-pencil-square"></i></button></a>
<a href="{% url 'profesores:profesores_delete' profesor.id %}"><button class="btn btn-danger">Eliminar<i class="bi bi-trash-fill"></i></button></a>
<div class="p-3" > <a href="{% url 'profesores:profesores_list' %}"><button class="btn btn-secondary">Volver <i class="bi bi-arrow-left-square-fill"></i></button></a></div>
    
{% endblock content-right %}

profesores/templates/profesores/profesor_form.html
{% extends 'home/index.html' %}

{% block tittle %}
    <h1>Crear Profesor </h1>
{% endblock tittle %}

{% block content-left %}
    <form action="" method="post">
        <div class="mb-3">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary" >Guardar</button>
        </div>
    </form>


{% endblock content-left %}

{% block content-right %}
<div class="p-3" > <a href="{% url 'profesores:profesores_list' %}"><button class="btn btn-secondary">Volver <i class="bi bi-arrow-left-square-fill"></i></button></a></div>
{% endblock content-right %}

profesores/templates/profesores/profesor_list.html
{% extends 'home/index.html' %}

{% block titulo %}
    <title>Profesores</title>
{% endblock titulo %}

{% block tittle %}
<div class="container">
    <h1>Listado de profesores </h1>
</div>
    
{% endblock tittle %}

{% block content-left %}
    <div class="py-4 text-center">
        <form action="" method="GET">
            <input type="text" name="buscar" placeholder="Buscar" class="form-control"> 
            <button class="btn btn-primary m-2" type="submit">Buscar</button>
            <button class="btn btn-primary m-2" >Todos</button>
        </form>
    </div>

    <ul class="list-group">
        {% for profesor in object_list %}
        <li class="list-group-item list-group-item-info"> {{profesor.nombre}}  {{profesor.apellido}}
            <a class="float-end" href="{% url 'profesores:profesores_detail' profesor.id %}"><button class="btn btn-info">Detalles <i class="bi bi-eye"></i></button></a>
        </li>
        
      
    {% endfor %}

    </ul>
    
{% endblock content-left %}
  
{% block content-right %}

    <a href="{% url 'profesores:profesores_create' %}"><button class="btn btn-success">Agregar <i class="bi bi-file-earmark-plus"></i></button></a>
    <div class="p-3" > <a href="{% url 'home:index' %}"><button class="btn btn-secondary">Volver <i class="bi bi-arrow-left-square-fill"></i></button></a></div>
{% endblock content-right %}