config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

]
urlpatterns+=[
    path("", include("home.urls")),
    path("estudiantes/", include("estudiantes.urls")),
    path("profesores/", include("profesores.urls")),
    path("cursos/", include("cursos.urls")),
]

cursos/urls.py
from django.urls import path
from . import views

app_name="cursos"

urlpatterns = [
    path("",views.CursosList.as_view(),name="cursos_list"),
    path("detail/<int:pk>",views.CursosDetail.as_view(),name="cursos_detail"),
    path("crear/",views.CursosCreate.as_view(),name="cursos_create"),
    path("actualizar/<int:pk>",views.CursosUpdate.as_view(),name="cursos_update"),
    path("borrar/<int:pk>",views.CursosDelete.as_view(),name="cursos_delete"),
]

home/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name="home"

urlpatterns = [
    path("",views.index, name="index"),
    path("about/",views.about, name="about"),
    path("login/",views.login_request, name="login"),
    path("register/",views.register, name="register"),
    path("logout/",LogoutView.as_view(template_name="home/index.html"), name="logout")
]
urlpatterns += staticfiles_urlpatterns()

cursos/models.py
from django.db import models

# Create your models here.
class Curso(models.Model):
    curso=models.CharField(max_length=100)
    camada=models.CharField(max_length=100)
    
    

    def __str__(self) -> str:
        return f"{self.curso} {self.camada}"

cursos/forms.py
from django import forms
from . import models

class CursoForm(forms.ModelForm):
    class Meta:
        model= models.Curso
        fields=["curso","camada"]
    
        widgets= {
                "curso":forms.TextInput(attrs={"class":"form-control"}),
                "camada":forms.TextInput(attrs={"class":"form-control"})
            }

cursos/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView , DeleteView
from . import models
from . import forms


# Create your views here.

class CursosList(ListView):
    model = models.Curso

    def get_queryset(self):
        object_list = models.Curso.objects.all()
        if self.request.GET.get("buscar"):
            consulta = self.request.GET.get("buscar")
            object_list = models.Curso.objects.filter(
                curso__icontains=consulta
            )
        return object_list

class CursosDetail(DetailView):
    model = models.Curso

class CursosCreate(LoginRequiredMixin,CreateView):
    login_url = 'home:login'
    model = models.Curso
    form_class = forms.CursoForm
    success_url=reverse_lazy("cursos:cursos_list")

class CursosUpdate(LoginRequiredMixin,UpdateView):
    login_url = 'home:login'
    model = models.Curso
    form_class = forms.CursoForm
    success_url=reverse_lazy("cursos:cursos_list")

class CursosDelete(LoginRequiredMixin,DeleteView):
    login_url = 'home:login'
    model = models.Curso
    success_url=reverse_lazy("cursos:cursos_list")

cursos/templates/cursos/crear.html
{% extends 'home/index.html' %}

{% block tittle %}
    <h1>CREAR CURSO </h1>
{% endblock tittle %}

{% block content-left %}
    <form action="" method="post">
        <div class="mb-3">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary" >Guardar</button>
        </div>
    </form>


{% endblock content-left %}

{% block content-right %}

{% endblock content-right %}

cursos/templates/cursos/curso_confirm_delete.html
{% extends 'home/index.html' %}

{% block titulo %}
    <title>Cursos</title>
{% endblock titulo %}

{% block tittle %}
<div class="container">
    <h1>Eliminar curso </h1>
</div>
    
{% endblock tittle %}

{% block content-left %}
  <p> esta seguro que desea eliminar {{object.curso}} {{object.camada}}?</p>
  <form action="" method="post">
    <div class="mb-3">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-danger" >Eliminar</button>
    </div>
</form>
{% endblock content-left %}

    
{% block content-right %}
    <a href="{% url 'cursos:cursos_list' %}"><button class="btn btn-secondary">Volver <i class="bi bi-arrow-left-square-fill"></i></button></a>
{% endblock content-right %}

cursos/templates/cursos/curso_detail.html
{% extends 'home/index.html' %}

{% block titulo %}
    <title>Cursos</title>
{% endblock titulo %}

{% block tittle %}
<div class="container">
    <h1>Detalles de curso </h1>
</div>
    
{% endblock tittle %}

{% block content-left %}
    <ul class="list-group">
       
        <li class="list-group-item list-group-item-info"><strong>Curso:</strong>  {{object.curso}} </li>
        <li class="list-group-item list-group-item-info"> Camada: {{object.camada}}  </li>
      
    </ul>
    
{% endblock content-left %}

    
{% block content-right %}
<a href="{% url 'cursos:cursos_update' curso.id %}"><button class="btn btn-warning">Editar<i class="bi bi-pencil-square"></i></button></a>
<a href="{% url 'cursos:cursos_delete' curso.id %}"><button class="btn btn-danger">Eliminar<i class="bi bi-trash-fill"></i></button></a>
<div class="p-3" > <a href="{% url 'cursos:cursos_list' %}"><button class="btn btn-secondary">Volver <i class="bi bi-arrow-left-square-fill"></i></button></a></div>
    
{% endblock content-right %}

cursos/templates/cursos/curso_form.html
{% extends 'home/index.html' %}

{% block tittle %}
    <h1>Crear Curso </h1>
{% endblock tittle %}

{% block content-left %}
    <form action="" method="post">
        <div class="mb-3">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary" >Guardar</button>
        </div>
    </form>


{% endblock content-left %}

{% block content-right %}
<div class="p-3" > <a href="{% url 'cursos:cursos_list' %}"><button class="btn btn-secondary">Volver <i class="bi bi-arrow-left-square-fill"></i></button></a></div>
{% endblock content-right %}

cursos/templates/cursos/curso_list.html
{% extends 'home/index.html' %}

{% block titulo %}
    <title>Cursos</title>
{% endblock titulo %}

{% block tittle %}
<div class="container">
    <h1>Listado de Cursos </h1>
</div>
    
{% endblock tittle %}

{% block content-left %}
    <div class="py-4 text-center">
        <form action="" method="GET">
            <input type="text" name="buscar" placeholder="Buscar" class="form-control"> 
            <button class="btn btn-primary m-2" type="submit">Buscar</button>
            <button class="btn btn-primary m-2" >Todos</button>
        </form>
    </div>

    <ul class="list-group">
        {% for curso in object_list %}
        <li class="list-group-item list-group-item-info"> {{curso.curso}}  {{curso.camada}}
            <a class="float-end" href="{% url 'cursos:cursos_detail' curso.id %}"><button class="btn btn-info">Detalles <i class="bi bi-eye"></i></button></a>
        </li>
        
      
    {% endfor %}

    </ul>
    
{% endblock content-left %}
  
{% block content-right %}

    <a href="{% url 'cursos:cursos_create' %}"><button class="btn btn-success">Agregar <i class="bi bi-file-earmark-plus"></i></button></a>
    <div class="p-3" > <a href="{% url 'home:index' %}"><button class="btn btn-secondary">Volver <i class="bi bi-arrow-left-square-fill"></i></button></a></div>
{% endblock content-right %}